### ISSUE TITLE
Livestream

### ISSUE THREAD

**Issue by dannyshwan** [Capstone-QuickPass/frontend#35]
![Screen Shot 2020-10-26 at 9 30 14 PM](https://user-images.githubusercontent.com/34214482/97245913-747f4180-17d2-11eb-94aa-79e74e191ed9.png)

As of right now, we have a dashboard component that displays an overview of the various data we currently have. What we can try to implement before midterm, is to have a video stream from the raspberryPi onto the webapp. In addition, the dashboard is currently the only view we have. Since the live stream should probably be placed in a different view, we should look to integrate react-router. The path to the router file is as seen below:

![Screen Shot 2020-11-23 at 7 56 39 PM](https://user-images.githubusercontent.com/34214482/100032643-78e54d00-2dc6-11eb-848b-a5c05d9430b8.png)

## Task
Create a new component such that when the user clicks on the "stream" button, the view should display the video stream instead of the "dashboard overview". 

Set up react-router such that when the user clicks on the "stream button", the URL in the browser is set to localhost:8080/("whatever you name it")

**Comment by Keitech** [comment]
Once the stream component is working we can implement a tile to display the stream status, ex: **Live** or **Offline**

**Comment by dannyshwan** [comment]
Mostly done as of Feb 20th
