### ISSUE TITLE
Reorganize project

### ISSUE THREAD

**Issue by guptaharsh25** [Capstone-QuickPass/frontend#45]
Proposed file structure for `src` folder:
- components
  - Dashboard
    - Dashboard.tsx
    - styled.tsx
    - index.ts
    - Folder for a component used in Dashboard (PiChart)
      - PiChart.tsx
      - styled.tsx
      - index.ts
...
- App.tsx

**Comment by dannyshwan** [comment]
Done as of Feb 20th
